### ISSUE TITLE
顶部页签增加堆叠选项

### ISSUE THREAD

**Issue by HowcanoeWang** [royc01/notion-theme#12]
参考dark+主题的模式，这样堆叠页签可能查看起来更方便？

<img width="715" alt="image" src="https://user-images.githubusercontent.com/19968935/167346081-bf11aadc-a7f3-497f-a22c-5f7be7ac473b.png">

只需要增加一个`flex-wrap: wrap;`到.layout-tab-bar里面
```css
.layout-tab-bar {
    background-color: var(--b3-theme-background);
    flex-wrap: wrap;
}
```

css改扁，注释掉padding
```css
.layout-tab-bar .item{
	flex:unset; 
	background-color: var(--b3-theme-background);
	/* padding: 8px 0 6px 14px; */
	max-width:150px;
	box-shadow: none;
	border-radius: 0px;
}
```

要是能给个开关切换就更好了
