### ISSUE TITLE
主题默认设置，侧边栏出现白色顶部，会遮挡住悬浮菜单

### ISSUE THREAD

**Issue by moonxorsun** [royc01/notion-theme#135]
![image](https://user-images.githubusercontent.com/69239105/211501290-f7165628-7517-4ce6-9830-d7a40b261cbb.png)

如上图所示，经过摸索，加入以下代码貌似可以解决，不确定有无其他问题

```css
/* ————————————————————页签———————————————————— */
.layout-tab-bar:empty{
	padding:0 0 0 8px;
	position:relative;
	background-color: var(--b3-theme-background);
	height: 0px;
	z-index:2;
	box-shadow: 0 1px 0 0 var(--b3-border-color2);

}
.layout-tab-bar{
	padding:0 0 0 8px;
	position:relative;
	background-color: var(--b3-theme-background);
	height: 40px;
	z-index:2;
	box-shadow: 0 1px 0 0 var(--b3-border-color2);

}
```
修改后图示
![image](https://user-images.githubusercontent.com/69239105/211502184-74362c5f-3201-40e0-b6cd-6bb9a2d6251d.png)
