### ISSUE TITLE
文档标签在右边时，无法点击close按钮

### ISSUE THREAD

**Issue by yss930819** [royc01/notion-theme#189]
![2023-05-26 11 06 18](https://github.com/royc01/notion-theme/assets/8181260/073bb8fd-f41f-4adc-8553-1fed0797aad0)

右边有其他东西遮挡，无法点击到关闭按钮。
目前，我个人是吧标签改到 左侧使用

``` css
.b3-chips{
	float:left;
	z-index:10;
}
```
