### ISSUE TITLE
修改塊引用樣式的代碼片段疑問

### ISSUE THREAD

**Issue by Louie997** [royc01/notion-theme#222]
之前的版本可以用下面的代碼片段修改塊引用的樣式，讓塊引用不顯示背景，以及字體大小顯示為 100%
```css
.protyle-wysiwyg [data-node-id] span[data-type*="block-ref"]:not([data-type="virtual-block-ref"]){
	font-size: 100%;
	padding:0px 0px 0px 0px;
	background-color:transparent;
}
.protyle-wysiwyg [data-node-id] span[data-type="block-ref"]:hover{
	background-color:var(--b3-block-ref-background);
}
``` 
但最近更新後失效了，請問如何修改代碼片段，讓塊引用不顯示背景，以及字體大小顯示為 100%？

**Comment by Louie997** [comment]
找到失效的原因了，更新後塊引用樣式的CSS檔案被移到這個路徑底下了：`/appearance/themes/Savor/style/module/editor.css`

根據這個CSS檔有關塊引用樣式的程式碼，
添加以下代碼片段即可（字體大小顯示為 100%、去掉 padding 、背景透明）：
```css
.protyle-wysiwyg [data-node-id] span[data-type*="block-ref"]:not([data-type="virtual-block-ref"]):not([data-type*="sup"]):not([data-type*="sub"]){
	font-size: 100%;
	padding: 0;
	background-color: transparent;
}
```
