### ISSUE TITLE
写了个 CSS 片段，有用的话可以按需加到 Savor 主题里

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#282]
![image](https://github.com/royc01/notion-theme/assets/78434827/3c406461-d8f8-48dd-9e02-ce8f58fd38a7)

**Comment by TCOTC** [comment]
改进了一点：

```css
/*自定义页签最小宽度 CSS片段 （Savor主题自用）*/
.layout-tab-bar .item:not(.item--pin):not(.item--readonly)[data-type="tab-header"] {
    min-width: 105px; /*调整页签的最小宽度，只改这个值就可以了，其他代码不需要动*/
}

 /*调整叉号样式*/
.layout-tab-bar .item:not(.item--pin):not(.item--readonly)[data-type="tab-header"] .item__text {
    padding-right: 28px; /*调整叉号与标题文本间的最小距离*/
    /*max-width: calc(100% - 61px); /*使叉号不与标题文本重叠（废弃）*/
}
.layout-tab-bar .item:not(.item--pin):not(.item--readonly)[data-type="tab-header"] .item__close {
    background-color: var(--b3-card-error-background); /*使叉号不与标题文本重叠*/
    -webkit-mask-image: linear-gradient(to right, rgba(0, 0, 0, 0) 0, #000 5px); /*标题文本渐变*/
}
.layout-tab-bar .item:not(.item--pin):not(.item--readonly)[data-type="tab-header"] .item__close {
    position: absolute; /*让叉号靠右*/
    right: 0px;
    padding-left: 6px; /*扩大叉号点击范围*/
}
.layout-tab-bar .item:hover .item__close svg, .layout-tab-bar .item .item__close svg {
    opacity: .68; /*始终显示页签叉号*/
}

/*给页签添加背景色*/
.layout-tab-bar .item:not(.item--pin):not(.item--readonly)[data-type="tab-header"] {
    background-color: var(--b3-card-error-background);
}
```

**Comment by quentin-qiao** [comment]
Nice

**Comment by TCOTC** [comment]
又写了一个，效果可见：[代码片段｜反链 & 提及面板，固定文档名称 - 链滴](https://ld246.com/article/1699535322926)

```css
/* 反链&提及面板固定文档名称 CSS片段 */
.backlinkMList .b3-list-item,
.backlinkList .b3-list-item {
    --b3-theme-primary-lightest: var(--b3-theme-surface, #e9e5de) !important;
    --b3-list-hover: var(--b3-theme-surface, #e9e5de) !important;
    position: sticky;
    top: 0;
    z-index: 2;
    background-color: var(--b3-theme-surface, #e9e5de) !important;
}
```
