### ISSUE TITLE
Feature | Callout 内部引述块的第一个段落块不应该设置为大字体

### ISSUE THREAD

**Issue by frostime** [royc01/notion-theme#286]
如题所示：

![image](https://github.com/royc01/notion-theme/assets/27268127/f659f14b-1601-4cab-bfd0-be2dc0b09161)

个人认为，这样才更加合理一点：
![image](https://github.com/royc01/notion-theme/assets/27268127/cd60fb30-d5fa-471d-8497-6533db27b2a7)

具体做法：将 `.bq[custom-b~=bell] .p:first-child` 改为 `.bq[custom-b~=bell]>.p:first-child` 

```css
/*引述callout第一行样式 */
.bq[custom-b]>.p:first-child,
.bq[custom-b]>[data-type="NodeHeading"]:first-child {
    font-weight: 700 !important;
    font-size: 1.3em !important;
    padding: 0em 0em 0em 1.7em;
}
```
