### ISSUE TITLE
数据库上下按钮大小不等

### ISSUE THREAD

**Issue by TCOTC** [royc01/notion-theme#296]
https://github.com/royc01/notion-theme/blob/256fa1415c6a66d9b63e8b09f8cd3cad750b743c/theme.css#L514C1-L516C2

```css
.av__views .block__icon svg{
	width: 14px;
}
```

这个会导致数据库上下按钮大小不等：

默认主题：

![image](https://github.com/royc01/notion-theme/assets/78434827/704ecfc9-2156-4e62-8aaf-175fe3509fa2)

写味主题：

![image](https://github.com/royc01/notion-theme/assets/78434827/cc396270-c562-459b-96d8-54c0c7305deb)
